Relatorio.API/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Relatorio.Core.Models;

namespace Relatorio.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Relatorio.API/Controllers/RelatorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Relatorio.Core.Interfaces;
using Relatorio.Data.Context;

namespace Relatorio.Controllers
{
    public class RelatorioController : Controller
    {
        private readonly IRelatorioRepository _repositorio;

        private readonly IMessageBusPublishService _messageBus;

        public RelatorioController(IRelatorioRepository repositorio, IMessageBusPublishService messageBus)
        {
            _repositorio = repositorio;
            _messageBus = messageBus;
        }

        [HttpGet]
        public async Task<ActionResult<List<Core.Models.Relatorio>>> Index()
        {
            var relatorios = await _repositorio.ObterTodosRelatorios();

            return View(relatorios);
        }

        public ActionResult Health()
        {
            return Redirect("/dashboard");
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Relatorio.Core.Models.Relatorio relatorio)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _repositorio.AdicionarRelatorio(relatorio);

                    var json = JsonConvert.SerializeObject(relatorio);
                    
                    var body = Encoding.UTF8.GetBytes(json);

                    _messageBus.Publish("Relatorios", body);

                    return RedirectToAction("Index");
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError(string.Empty, $"Something went wrong {ex.Message}");
                }
            }

            ModelState.AddModelError(string.Empty, $"Something went wrong, invalid model");

            return View();
        }        
    }
}

Relatorio.API/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Relatorio.API/Views/Relatorio/Create.cshtml
@using Relatorio.Core.Models
@model Relatorio

<h2>Novo Relatório</h2>

<form asp-action="Create" method="post">
    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            <label asp-for="TipoRelatorio" class="col-md-4 control-label"></label>
            <div class="col-md-10">
                <select name="tipoRelatorio" class="form-control" asp-for="TipoRelatorio" onchange="inserirDuracao(this.value)">
                    <option value="">Selecione um tipo de relatório</option>
                    <option value="Vendas">Vendas</option>
                    <option value="Estoque">Estoque</option>
                    <option value="Faturamento">Faturamento</option>
                </select>
                <span asp-validation-for="TipoRelatorio" class="text-danger"></span>
            </div>
            <br />
            <label asp-for="Duracao" class="col-md-4 control-label"></label>
            <div class="col-md-10">
                <input type="text" asp-for="Duracao" id="duracao" value="0" readonly>
                <span asp-validation-for="Duracao" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-info">Retornar</a>
            </div>
        </div>
    </div>
</form>

<script src="~/js/duracao.js" asp-append-version="true"></script>

Relatorio.API/Views/Relatorio/Index.cshtml
@model IEnumerable<Relatorio>
@{string className = ""; string status = "";}
    
<h2>Solicitação de relatório</h2>
<hr />
<div class="row">
    <div class="col-md-12">
        <div>
            <div class="pull-left">
                <a asp-action="Create" class="btn btn-primary">
                    <span title="Incluir Livro" class="fas fa-plus"></span> Solicitar Relatório
                </a>
            </div>
        </div>
    </div>
</div>
<br />
<div class="panel panel-default">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.TipoRelatorio)
                </th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                @if(item.Concluido)
                {
                    className = "success";
                    status = "CONCLUÍDO";
                }
                else
                {
                    className = "info";
                    status = "PENDENTE";
                }
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TipoRelatorio)
                    </td>
                    <td>
                        <a id='relatorio-item-color-@item.Id' class='btn btn-@className disabled' style="color: white;">
                            <span class="fas fa-edit" id="relatorio-item-status-@item.Id">@status</span>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/signal.js"></script>

Relatorio.API/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Relatório</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Relatorio" asp-action="Index">Relatório</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Relatorio" asp-action="Health">Health Checks</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Relatorio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>